name: Generate PNG from drawio

on:
  push:
    branches: [main]

jobs:
  generate_png:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure we get the full commit history

      - name: Install drawio-cli
        run: |
          sudo wget https://github.com/jgraph/drawio-desktop/releases/download/v14.8.5/drawio-14.8.5-amd64.deb
          sudo dpkg -i drawio-14.8.5-amd64.deb

      - name: Generate PNG
        run: |
          drawio -x -f png -o ${{ secrets.FILENAME }} ${{ github.workspace }}/mockup.drawio

      - name: Commit PNG
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.event.head_commit.author.name }}
          author_email: ${{ github.event.head_commit.author.email }}
          message: "Add PNG for ${{ github.event.head_commit.message }}"
          add: ${{ secrets.FILENAME }}
