name: Draw.io Export

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install draw.io
        run: |
          sudo apt-get update
          sudo apt install snapd
          sudo snap install drawio
